name: Psych Ultra Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.2

      - name: Cache Haxelib
        uses: actions/cache@v3
        with:
          path: C:\Users\runneradmin\haxelib
          key: haxelib-${{ runner.os }}

      - name: Install Dependencies
        run: |
          haxelib install flixel -y
          haxelib install lime -y
          haxelib install openfl -y

      - name: Build Windows
        run: lime build windows -release

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: export/